version: '3.8'

services:
  backendapi:
    image: backendapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION_STRING=redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
