// <auto-generated />
using System;
using BackendApi.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240930101429_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.LogsOfPaymentCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Customerid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customerid");

                    b.ToTable("PaymentLog");
                });

            modelBuilder.Entity("BackendApi.models.ApprovalPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalPayment");
                });

            modelBuilder.Entity("BackendApi.models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BackendApi.models.Customer", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("Spend")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BackendApi.models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BackendApi.models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("BackendApi.models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4774),
                            Description = "Latest model with cutting-edge technology.",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 699
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4809),
                            Description = "High performance laptop for professionals.",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 1299
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4811),
                            Description = "Noise-cancelling over-ear headphones.",
                            IsAvailable = true,
                            Name = "Headphones",
                            Price = 199
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4813),
                            Description = "Smartwatch with health tracking features.",
                            IsAvailable = false,
                            Name = "Smartwatch",
                            Price = 249
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4815),
                            Description = "Portable tablet with high-resolution display.",
                            IsAvailable = true,
                            Name = "Tablet",
                            Price = 499
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4816),
                            Description = "High-performance gaming PC with the latest GPU.",
                            IsAvailable = true,
                            Name = "Gaming PC",
                            Price = 1999
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4818),
                            Description = "27-inch 144Hz gaming monitor for smooth gameplay.",
                            IsAvailable = true,
                            Name = "Gaming Monitor",
                            Price = 349
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4820),
                            Description = "RGB mechanical keyboard with customizable keys.",
                            IsAvailable = true,
                            Name = "Mechanical Keyboard",
                            Price = 129
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4823),
                            Description = "High-precision gaming mouse with adjustable DPI.",
                            IsAvailable = true,
                            Name = "Gaming Mouse",
                            Price = 59
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4824),
                            Description = "Top-of-the-line graphics card for gaming.",
                            IsAvailable = true,
                            Name = "Graphics Card",
                            Price = 499
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4826),
                            Description = "High-performance CPU for gaming and multitasking.",
                            IsAvailable = true,
                            Name = "Processor",
                            Price = 299
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4828),
                            Description = "Gaming motherboard with RGB lighting and advanced features.",
                            IsAvailable = true,
                            Name = "Motherboard",
                            Price = 199
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4830),
                            Description = "Ergonomic gaming chair for long hours of play.",
                            IsAvailable = true,
                            Name = "Gaming Chair",
                            Price = 249
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4831),
                            Description = "1TB SSD for faster load times in games.",
                            IsAvailable = true,
                            Name = "SSD 1TB",
                            Price = 129
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4833),
                            Description = "2TB HDD for additional storage.",
                            IsAvailable = true,
                            Name = "HDD 2TB",
                            Price = 69
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4869),
                            Description = "Immersive VR headset for gaming.",
                            IsAvailable = true,
                            Name = "VR Headset",
                            Price = 399
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4871),
                            Description = "Latest generation game console.",
                            IsAvailable = true,
                            Name = "Game Console",
                            Price = 499
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4873),
                            Description = "Wireless controller for gaming consoles.",
                            IsAvailable = true,
                            Name = "Controller",
                            Price = 59
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4875),
                            Description = "Spacious desk designed for gaming setups.",
                            IsAvailable = true,
                            Name = "Gaming Desk",
                            Price = 199
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4877),
                            Description = "High-definition webcam for streaming.",
                            IsAvailable = true,
                            Name = "Webcam",
                            Price = 89
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4878),
                            Description = "USB microphone for clear audio during streams.",
                            IsAvailable = true,
                            Name = "Microphone",
                            Price = 129
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4880),
                            Description = "Capture card for streaming console gameplay.",
                            IsAvailable = true,
                            Name = "Capture Card",
                            Price = 149
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4882),
                            Description = "Blue light blocking glasses for gamers.",
                            IsAvailable = true,
                            Name = "Gaming Glasses",
                            Price = 39
                        },
                        new
                        {
                            Id = 24,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4884),
                            Description = "Monthly subscription for access to a library of games.",
                            IsAvailable = true,
                            Name = "Game Subscription",
                            Price = 59
                        },
                        new
                        {
                            Id = 25,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4885),
                            Description = "Gift card for purchasing games online.",
                            IsAvailable = true,
                            Name = "Game Gift Card",
                            Price = 50
                        },
                        new
                        {
                            Id = 26,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4887),
                            Description = "High-speed router optimized for gaming.",
                            IsAvailable = true,
                            Name = "Gaming Router",
                            Price = 99
                        },
                        new
                        {
                            Id = 27,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4890),
                            Description = "500GB portable SSD for on-the-go gaming.",
                            IsAvailable = true,
                            Name = "Portable SSD 500GB",
                            Price = 79
                        },
                        new
                        {
                            Id = 28,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4892),
                            Description = "Stereo headset with built-in microphone.",
                            IsAvailable = true,
                            Name = "Gaming Headset",
                            Price = 99
                        },
                        new
                        {
                            Id = 29,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4894),
                            Description = "Versatile gamepad for various consoles.",
                            IsAvailable = true,
                            Name = "Gamepad",
                            Price = 49
                        },
                        new
                        {
                            Id = 30,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4896),
                            Description = "Large RGB mouse pad for gaming.",
                            IsAvailable = true,
                            Name = "RGB Mouse Pad",
                            Price = 29
                        },
                        new
                        {
                            Id = 31,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4898),
                            Description = "Storage solution for game discs and accessories.",
                            IsAvailable = true,
                            Name = "Game Storage Box",
                            Price = 19
                        },
                        new
                        {
                            Id = 32,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4900),
                            Description = "Cooling pad for laptops during long gaming sessions.",
                            IsAvailable = true,
                            Name = "Gaming Cooling Pad",
                            Price = 39
                        },
                        new
                        {
                            Id = 33,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4901),
                            Description = "VR games for immersive experiences.",
                            IsAvailable = true,
                            Name = "Virtual Reality Games",
                            Price = 39
                        },
                        new
                        {
                            Id = 34,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4903),
                            Description = "Compact pouch for gaming accessories.",
                            IsAvailable = true,
                            Name = "Gaming Pouch",
                            Price = 15
                        },
                        new
                        {
                            Id = 35,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4905),
                            Description = "Software for creating your own games.",
                            IsAvailable = true,
                            Name = "Game Development Software",
                            Price = 299
                        },
                        new
                        {
                            Id = 36,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4907),
                            Description = "Art book featuring designs from popular games.",
                            IsAvailable = true,
                            Name = "Game Art Book",
                            Price = 25
                        },
                        new
                        {
                            Id = 37,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4909),
                            Description = "Comprehensive strategy guide for popular games.",
                            IsAvailable = true,
                            Name = "Gaming Strategy Guide",
                            Price = 20
                        },
                        new
                        {
                            Id = 38,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4911),
                            Description = "Comfortable t-shirt for gamers.",
                            IsAvailable = true,
                            Name = "Gaming T-shirt",
                            Price = 24
                        },
                        new
                        {
                            Id = 39,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4912),
                            Description = "Warm hoodie for gamers.",
                            IsAvailable = true,
                            Name = "Gaming Hoodie",
                            Price = 49
                        },
                        new
                        {
                            Id = 40,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4914),
                            Description = "Figures from popular game franchises.",
                            IsAvailable = true,
                            Name = "Collectible Figurines",
                            Price = 34
                        },
                        new
                        {
                            Id = 41,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4916),
                            Description = "Cable management solution for gaming mice.",
                            IsAvailable = true,
                            Name = "Gaming Mouse Bungee",
                            Price = 19
                        },
                        new
                        {
                            Id = 42,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4918),
                            Description = "Stand for organizing gaming consoles.",
                            IsAvailable = true,
                            Name = "Console Stand",
                            Price = 29
                        },
                        new
                        {
                            Id = 43,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4919),
                            Description = "Holds multiple game cards securely.",
                            IsAvailable = true,
                            Name = "Game Card Holder",
                            Price = 15
                        },
                        new
                        {
                            Id = 44,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4921),
                            Description = "Protective mat for gaming chairs.",
                            IsAvailable = true,
                            Name = "Gaming Chair Mat",
                            Price = 39
                        },
                        new
                        {
                            Id = 45,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4923),
                            Description = "Lighting for enhancing streaming quality.",
                            IsAvailable = true,
                            Name = "Streaming Light",
                            Price = 59
                        },
                        new
                        {
                            Id = 46,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4925),
                            Description = "Posters and wall art for gamers.",
                            IsAvailable = true,
                            Name = "Game Theme Wall Art",
                            Price = 49
                        },
                        new
                        {
                            Id = 47,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4927),
                            Description = "Portable monitor for gaming on the go.",
                            IsAvailable = true,
                            Name = "Portable Gaming Monitor",
                            Price = 299
                        },
                        new
                        {
                            Id = 48,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4929),
                            Description = "Gift card for purchasing games on Steam.",
                            IsAvailable = true,
                            Name = "Steam Gift Card",
                            Price = 50
                        },
                        new
                        {
                            Id = 49,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4930),
                            Description = "Gift card for purchasing games on Epic Games Store.",
                            IsAvailable = true,
                            Name = "Epic Games Gift Card",
                            Price = 50
                        },
                        new
                        {
                            Id = 50,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4932),
                            Description = "Monthly subscription box for gaming goodies.",
                            IsAvailable = true,
                            Name = "Gaming Subscription Box",
                            Price = 39
                        },
                        new
                        {
                            Id = 51,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4934),
                            Description = "Full-sized arcade machine for home use.",
                            IsAvailable = true,
                            Name = "Arcade Machine",
                            Price = 999
                        },
                        new
                        {
                            Id = 52,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4936),
                            Description = "Everything you need for a gaming LAN party.",
                            IsAvailable = true,
                            Name = "Gaming LAN Party Kit",
                            Price = 199
                        },
                        new
                        {
                            Id = 53,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4937),
                            Description = "Guide to building the ultimate gaming setup.",
                            IsAvailable = true,
                            Name = "Pro Gaming Setup Guide",
                            Price = 29
                        },
                        new
                        {
                            Id = 54,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4939),
                            Description = "Complete setup for game streaming.",
                            IsAvailable = true,
                            Name = "Game Streaming Setup",
                            Price = 399
                        },
                        new
                        {
                            Id = 55,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4941),
                            Description = "Books about gaming culture.",
                            IsAvailable = true,
                            Name = "Gaming Lifestyle Book",
                            Price = 20
                        },
                        new
                        {
                            Id = 56,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4943),
                            Description = "Console with classic games from the past.",
                            IsAvailable = true,
                            Name = "Retro Gaming Console",
                            Price = 149
                        },
                        new
                        {
                            Id = 57,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4944),
                            Description = "Jewelry for gamers.",
                            IsAvailable = true,
                            Name = "Gaming Jewelry",
                            Price = 24
                        },
                        new
                        {
                            Id = 58,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4946),
                            Description = "Costumes based on popular game characters.",
                            IsAvailable = true,
                            Name = "Game Character Costume",
                            Price = 89
                        },
                        new
                        {
                            Id = 59,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4948),
                            Description = "Join a community of gamers.",
                            IsAvailable = true,
                            Name = "Gaming Community Membership",
                            Price = 19
                        },
                        new
                        {
                            Id = 60,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4950),
                            Description = "Controller for mobile gaming.",
                            IsAvailable = true,
                            Name = "Mobile Gaming Controller",
                            Price = 39
                        },
                        new
                        {
                            Id = 61,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4951),
                            Description = "Get a custom-built gaming PC.",
                            IsAvailable = true,
                            Name = "Custom PC Building Service",
                            Price = 199
                        },
                        new
                        {
                            Id = 62,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4957),
                            Description = "Comfortable socks with game themes.",
                            IsAvailable = true,
                            Name = "Game Themed Socks",
                            Price = 15
                        },
                        new
                        {
                            Id = 63,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4959),
                            Description = "Access to various games for a monthly fee.",
                            IsAvailable = true,
                            Name = "Gaming Subscription Service",
                            Price = 49
                        },
                        new
                        {
                            Id = 64,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4961),
                            Description = "Your personal arcade at home.",
                            IsAvailable = true,
                            Name = "Home Arcade Cabinet",
                            Price = 899
                        },
                        new
                        {
                            Id = 65,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4962),
                            Description = "Learn how to stream games effectively.",
                            IsAvailable = true,
                            Name = "Game Streaming Course",
                            Price = 99
                        },
                        new
                        {
                            Id = 66,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4964),
                            Description = "Vinyl records of popular game soundtracks.",
                            IsAvailable = true,
                            Name = "Game Soundtrack Vinyl",
                            Price = 29
                        },
                        new
                        {
                            Id = 67,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4966),
                            Description = "Glasses for enhanced 3D gaming experience.",
                            IsAvailable = true,
                            Name = "3D Gaming Glasses",
                            Price = 49
                        },
                        new
                        {
                            Id = 68,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4968),
                            Description = "Portable console for gaming on the go.",
                            IsAvailable = true,
                            Name = "Gaming Handheld Console",
                            Price = 199
                        },
                        new
                        {
                            Id = 69,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4969),
                            Description = "Recipes inspired by popular games.",
                            IsAvailable = true,
                            Name = "Gamer's Cookbook",
                            Price = 25
                        },
                        new
                        {
                            Id = 70,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4971),
                            Description = "Card for purchasing in-game currency.",
                            IsAvailable = true,
                            Name = "In-Game Currency Card",
                            Price = 20
                        },
                        new
                        {
                            Id = 71,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4973),
                            Description = "Pass for online gaming access.",
                            IsAvailable = true,
                            Name = "Online Game Pass",
                            Price = 29
                        },
                        new
                        {
                            Id = 72,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4975),
                            Description = "Workout gear designed for gamers.",
                            IsAvailable = true,
                            Name = "Gaming Workout Gear",
                            Price = 45
                        },
                        new
                        {
                            Id = 73,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4977),
                            Description = "Learn how to design your own games.",
                            IsAvailable = true,
                            Name = "Game Design Course",
                            Price = 199
                        },
                        new
                        {
                            Id = 74,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4978),
                            Description = "Art prints from popular games.",
                            IsAvailable = true,
                            Name = "Game Art Prints",
                            Price = 29
                        },
                        new
                        {
                            Id = 75,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4980),
                            Description = "Stay updated with the latest gaming news.",
                            IsAvailable = true,
                            Name = "Gaming News Subscription",
                            Price = 19
                        },
                        new
                        {
                            Id = 76,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4982),
                            Description = "Tools for aspiring game developers.",
                            IsAvailable = true,
                            Name = "Game Development Toolkit",
                            Price = 89
                        },
                        new
                        {
                            Id = 77,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4984),
                            Description = "Tickets for major e-sports events.",
                            IsAvailable = true,
                            Name = "E-sports Event Tickets",
                            Price = 100
                        },
                        new
                        {
                            Id = 78,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4985),
                            Description = "Cushion for added comfort in gaming chairs.",
                            IsAvailable = true,
                            Name = "Gaming Chair Cushion",
                            Price = 19
                        },
                        new
                        {
                            Id = 79,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4987),
                            Description = "Software for remaking classic games.",
                            IsAvailable = true,
                            Name = "Game Remake Software",
                            Price = 199
                        },
                        new
                        {
                            Id = 80,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4989),
                            Description = "Book filled with gaming challenges to try.",
                            IsAvailable = true,
                            Name = "Gaming Challenge Book",
                            Price = 24
                        },
                        new
                        {
                            Id = 81,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4991),
                            Description = "Organize your gaming accessories and gear.",
                            IsAvailable = true,
                            Name = "Gamer's Desk Organizer",
                            Price = 35
                        },
                        new
                        {
                            Id = 82,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4993),
                            Description = "Stress ball for gamers.",
                            IsAvailable = true,
                            Name = "Gaming Stress Ball",
                            Price = 10
                        },
                        new
                        {
                            Id = 83,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4995),
                            Description = "Protective skin for game controllers.",
                            IsAvailable = true,
                            Name = "Game Controller Skin",
                            Price = 15
                        },
                        new
                        {
                            Id = 84,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4997),
                            Description = "All you need for a perfect game night.",
                            IsAvailable = true,
                            Name = "Game Night Kit",
                            Price = 29
                        },
                        new
                        {
                            Id = 85,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(4998),
                            Description = "Art installation based on video games.",
                            IsAvailable = true,
                            Name = "Video Game Art Installation",
                            Price = 999
                        },
                        new
                        {
                            Id = 86,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5000),
                            Description = "Learn how to market your games effectively.",
                            IsAvailable = true,
                            Name = "Game Marketing Course",
                            Price = 99
                        },
                        new
                        {
                            Id = 87,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5002),
                            Description = "Get a professional trailer for your game.",
                            IsAvailable = true,
                            Name = "Game Trailer Production",
                            Price = 299
                        },
                        new
                        {
                            Id = 88,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5003),
                            Description = "One-on-one coaching for competitive gaming.",
                            IsAvailable = true,
                            Name = "Esports Coaching",
                            Price = 150
                        },
                        new
                        {
                            Id = 89,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5005),
                            Description = "Bag designed for transporting gaming gear.",
                            IsAvailable = true,
                            Name = "Gaming Travel Bag",
                            Price = 49
                        },
                        new
                        {
                            Id = 90,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5007),
                            Description = "Learn to develop games for mobile devices.",
                            IsAvailable = true,
                            Name = "Mobile Game Development Course",
                            Price = 199
                        },
                        new
                        {
                            Id = 91,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5009),
                            Description = "Guide to help gamers relax and focus.",
                            IsAvailable = true,
                            Name = "Gamer's Meditation Guide",
                            Price = 19
                        },
                        new
                        {
                            Id = 92,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5010),
                            Description = "Merchandise from popular game franchises.",
                            IsAvailable = true,
                            Name = "Game Merchandise",
                            Price = 29
                        },
                        new
                        {
                            Id = 93,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5012),
                            Description = "Tools and resources for training in e-sports.",
                            IsAvailable = true,
                            Name = "E-sports Training Kit",
                            Price = 199
                        },
                        new
                        {
                            Id = 94,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5014),
                            Description = "Access to exclusive gaming community forums.",
                            IsAvailable = true,
                            Name = "Gaming Community Forum Access",
                            Price = 10
                        },
                        new
                        {
                            Id = 95,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5016),
                            Description = "Software for designing video games.",
                            IsAvailable = true,
                            Name = "Game Design Software",
                            Price = 299
                        },
                        new
                        {
                            Id = 96,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5018),
                            Description = "CD of music from popular games.",
                            IsAvailable = true,
                            Name = "Game Soundtrack CD",
                            Price = 19
                        },
                        new
                        {
                            Id = 97,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5020),
                            Description = "Cooling pad designed for gaming laptops.",
                            IsAvailable = true,
                            Name = "Gaming Laptop Cooling Pad",
                            Price = 49
                        },
                        new
                        {
                            Id = 98,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5021),
                            Description = "Service for playtesting your game.",
                            IsAvailable = true,
                            Name = "Game Playtesting Service",
                            Price = 99
                        },
                        new
                        {
                            Id = 99,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5023),
                            Description = "Stay updated on gaming culture and trends.",
                            IsAvailable = true,
                            Name = "Gaming Culture Magazine Subscription",
                            Price = 29
                        },
                        new
                        {
                            Id = 100,
                            DateTime = new DateTime(2024, 9, 30, 12, 14, 29, 420, DateTimeKind.Local).AddTicks(5025),
                            Description = "A retreat focused on gamer wellness and community.",
                            IsAvailable = true,
                            Name = "Gamer's Wellness Retreat",
                            Price = 999
                        });
                });

            modelBuilder.Entity("BackendApi.models.Sponsors", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("BackendApi.Models.LogsOfPaymentCustomer", b =>
                {
                    b.HasOne("BackendApi.models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
