using BackendApi.models;
using Microsoft.EntityFrameworkCore;

namespace BackendApi.SeedData
{
    public static class ProductSeed
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Products>().HasData(
                // Existing products (1-25)
                new Products { Id = 1, Name = "Smartphone", Price = 699, Description = "Latest model with cutting-edge technology.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 2, Name = "Laptop", Price = 1299, Description = "High performance laptop for professionals.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 3, Name = "Headphones", Price = 199, Description = "Noise-cancelling over-ear headphones.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 4, Name = "Smartwatch", Price = 249, Description = "Smartwatch with health tracking features.", IsAvailable = false, DateTime = DateTime.Now },
                new Products { Id = 5, Name = "Tablet", Price = 499, Description = "Portable tablet with high-resolution display.", IsAvailable = true, DateTime = DateTime.Now },

                // Gaming Products (26-100)
                new Products { Id = 6, Name = "Gaming PC", Price = 1999, Description = "High-performance gaming PC with the latest GPU.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 7, Name = "Gaming Monitor", Price = 349, Description = "27-inch 144Hz gaming monitor for smooth gameplay.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 8, Name = "Mechanical Keyboard", Price = 129, Description = "RGB mechanical keyboard with customizable keys.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 9, Name = "Gaming Mouse", Price = 59, Description = "High-precision gaming mouse with adjustable DPI.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 10, Name = "Graphics Card", Price = 499, Description = "Top-of-the-line graphics card for gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 11, Name = "Processor", Price = 299, Description = "High-performance CPU for gaming and multitasking.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 12, Name = "Motherboard", Price = 199, Description = "Gaming motherboard with RGB lighting and advanced features.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 13, Name = "Gaming Chair", Price = 249, Description = "Ergonomic gaming chair for long hours of play.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 14, Name = "SSD 1TB", Price = 129, Description = "1TB SSD for faster load times in games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 15, Name = "HDD 2TB", Price = 69, Description = "2TB HDD for additional storage.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 16, Name = "VR Headset", Price = 399, Description = "Immersive VR headset for gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 17, Name = "Game Console", Price = 499, Description = "Latest generation game console.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 18, Name = "Controller", Price = 59, Description = "Wireless controller for gaming consoles.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 19, Name = "Gaming Desk", Price = 199, Description = "Spacious desk designed for gaming setups.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 20, Name = "Webcam", Price = 89, Description = "High-definition webcam for streaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 21, Name = "Microphone", Price = 129, Description = "USB microphone for clear audio during streams.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 22, Name = "Capture Card", Price = 149, Description = "Capture card for streaming console gameplay.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 23, Name = "Gaming Glasses", Price = 39, Description = "Blue light blocking glasses for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 24, Name = "Game Subscription", Price = 59, Description = "Monthly subscription for access to a library of games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 25, Name = "Game Gift Card", Price = 50, Description = "Gift card for purchasing games online.", IsAvailable = true, DateTime = DateTime.Now },

                // Additional Products (26-100)
                new Products { Id = 26, Name = "Gaming Router", Price = 99, Description = "High-speed router optimized for gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 27, Name = "Portable SSD 500GB", Price = 79, Description = "500GB portable SSD for on-the-go gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 28, Name = "Gaming Headset", Price = 99, Description = "Stereo headset with built-in microphone.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 29, Name = "Gamepad", Price = 49, Description = "Versatile gamepad for various consoles.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 30, Name = "RGB Mouse Pad", Price = 29, Description = "Large RGB mouse pad for gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 31, Name = "Game Storage Box", Price = 19, Description = "Storage solution for game discs and accessories.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 32, Name = "Gaming Cooling Pad", Price = 39, Description = "Cooling pad for laptops during long gaming sessions.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 33, Name = "Virtual Reality Games", Price = 39, Description = "VR games for immersive experiences.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 34, Name = "Gaming Pouch", Price = 15, Description = "Compact pouch for gaming accessories.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 35, Name = "Game Development Software", Price = 299, Description = "Software for creating your own games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 36, Name = "Game Art Book", Price = 25, Description = "Art book featuring designs from popular games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 37, Name = "Gaming Strategy Guide", Price = 20, Description = "Comprehensive strategy guide for popular games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 38, Name = "Gaming T-shirt", Price = 24, Description = "Comfortable t-shirt for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 39, Name = "Gaming Hoodie", Price = 49, Description = "Warm hoodie for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 40, Name = "Collectible Figurines", Price = 34, Description = "Figures from popular game franchises.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 41, Name = "Gaming Mouse Bungee", Price = 19, Description = "Cable management solution for gaming mice.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 42, Name = "Console Stand", Price = 29, Description = "Stand for organizing gaming consoles.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 43, Name = "Game Card Holder", Price = 15, Description = "Holds multiple game cards securely.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 44, Name = "Gaming Chair Mat", Price = 39, Description = "Protective mat for gaming chairs.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 45, Name = "Streaming Light", Price = 59, Description = "Lighting for enhancing streaming quality.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 46, Name = "Game Theme Wall Art", Price = 49, Description = "Posters and wall art for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 47, Name = "Portable Gaming Monitor", Price = 299, Description = "Portable monitor for gaming on the go.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 48, Name = "Steam Gift Card", Price = 50, Description = "Gift card for purchasing games on Steam.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 49, Name = "Epic Games Gift Card", Price = 50, Description = "Gift card for purchasing games on Epic Games Store.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 50, Name = "Gaming Subscription Box", Price = 39, Description = "Monthly subscription box for gaming goodies.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 51, Name = "Arcade Machine", Price = 999, Description = "Full-sized arcade machine for home use.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 52, Name = "Gaming LAN Party Kit", Price = 199, Description = "Everything you need for a gaming LAN party.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 53, Name = "Pro Gaming Setup Guide", Price = 29, Description = "Guide to building the ultimate gaming setup.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 54, Name = "Game Streaming Setup", Price = 399, Description = "Complete setup for game streaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 55, Name = "Gaming Lifestyle Book", Price = 20, Description = "Books about gaming culture.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 56, Name = "Retro Gaming Console", Price = 149, Description = "Console with classic games from the past.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 57, Name = "Gaming Jewelry", Price = 24, Description = "Jewelry for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 58, Name = "Game Character Costume", Price = 89, Description = "Costumes based on popular game characters.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 59, Name = "Gaming Community Membership", Price = 19, Description = "Join a community of gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 60, Name = "Mobile Gaming Controller", Price = 39, Description = "Controller for mobile gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 61, Name = "Custom PC Building Service", Price = 199, Description = "Get a custom-built gaming PC.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 62, Name = "Game Themed Socks", Price = 15, Description = "Comfortable socks with game themes.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 63, Name = "Gaming Subscription Service", Price = 49, Description = "Access to various games for a monthly fee.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 64, Name = "Home Arcade Cabinet", Price = 899, Description = "Your personal arcade at home.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 65, Name = "Game Streaming Course", Price = 99, Description = "Learn how to stream games effectively.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 66, Name = "Game Soundtrack Vinyl", Price = 29, Description = "Vinyl records of popular game soundtracks.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 67, Name = "3D Gaming Glasses", Price = 49, Description = "Glasses for enhanced 3D gaming experience.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 68, Name = "Gaming Handheld Console", Price = 199, Description = "Portable console for gaming on the go.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 69, Name = "Gamer's Cookbook", Price = 25, Description = "Recipes inspired by popular games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 70, Name = "In-Game Currency Card", Price = 20, Description = "Card for purchasing in-game currency.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 71, Name = "Online Game Pass", Price = 29, Description = "Pass for online gaming access.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 72, Name = "Gaming Workout Gear", Price = 45, Description = "Workout gear designed for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 73, Name = "Game Design Course", Price = 199, Description = "Learn how to design your own games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 74, Name = "Game Art Prints", Price = 29, Description = "Art prints from popular games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 75, Name = "Gaming News Subscription", Price = 19, Description = "Stay updated with the latest gaming news.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 76, Name = "Game Development Toolkit", Price = 89, Description = "Tools for aspiring game developers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 77, Name = "E-sports Event Tickets", Price = 100, Description = "Tickets for major e-sports events.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 78, Name = "Gaming Chair Cushion", Price = 19, Description = "Cushion for added comfort in gaming chairs.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 79, Name = "Game Remake Software", Price = 199, Description = "Software for remaking classic games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 80, Name = "Gaming Challenge Book", Price = 24, Description = "Book filled with gaming challenges to try.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 81, Name = "Gamer's Desk Organizer", Price = 35, Description = "Organize your gaming accessories and gear.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 82, Name = "Gaming Stress Ball", Price = 10, Description = "Stress ball for gamers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 83, Name = "Game Controller Skin", Price = 15, Description = "Protective skin for game controllers.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 84, Name = "Game Night Kit", Price = 29, Description = "All you need for a perfect game night.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 85, Name = "Video Game Art Installation", Price = 999, Description = "Art installation based on video games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 86, Name = "Game Marketing Course", Price = 99, Description = "Learn how to market your games effectively.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 87, Name = "Game Trailer Production", Price = 299, Description = "Get a professional trailer for your game.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 88, Name = "Esports Coaching", Price = 150, Description = "One-on-one coaching for competitive gaming.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 89, Name = "Gaming Travel Bag", Price = 49, Description = "Bag designed for transporting gaming gear.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 90, Name = "Mobile Game Development Course", Price = 199, Description = "Learn to develop games for mobile devices.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 91, Name = "Gamer's Meditation Guide", Price = 19, Description = "Guide to help gamers relax and focus.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 92, Name = "Game Merchandise", Price = 29, Description = "Merchandise from popular game franchises.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 93, Name = "E-sports Training Kit", Price = 199, Description = "Tools and resources for training in e-sports.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 94, Name = "Gaming Community Forum Access", Price = 10, Description = "Access to exclusive gaming community forums.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 95, Name = "Game Design Software", Price = 299, Description = "Software for designing video games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 96, Name = "Game Soundtrack CD", Price = 19, Description = "CD of music from popular games.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 97, Name = "Gaming Laptop Cooling Pad", Price = 49, Description = "Cooling pad designed for gaming laptops.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 98, Name = "Game Playtesting Service", Price = 99, Description = "Service for playtesting your game.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 99, Name = "Gaming Culture Magazine Subscription", Price = 29, Description = "Stay updated on gaming culture and trends.", IsAvailable = true, DateTime = DateTime.Now },
                new Products { Id = 100, Name = "Gamer's Wellness Retreat", Price = 999, Description = "A retreat focused on gamer wellness and community.", IsAvailable = true, DateTime = DateTime.Now }
            );
        }
    }
}
